# AUTOGENERATED! DO NOT EDIT! File to edit: app.ipynb.
# %% app.ipynb 41
!pip install gradio
from fastai.vision.all import *
import gradio as gr

def is_cat(x): return x[0].isupper()

# %% app.ipynb 43
learn = load_learner('model.pkl')

# %% app.ipynb 45
categories = ('Dog', 'Cat')

def classify_image(img):
    pred,idx,probs = learn.predict(img)
    return dict(zip(categories, map(float,probs)))

# %% app.ipynb 46
image = gr.inputs.Image(shape=(192, 192))
label = gr.outputs.Label()
examples = ['cat.jpg', 'dog.jpg', 'dunno.jpg']


intf = gr.Interface(fn=classify_image, inputs=image, outputs=label, examples=examples)
intf.launch(inline=False)
