# AUTOGENERATED! DO NOT EDIT! File to edit: app.ipynb.

# %% auto 0
__all__ = ['learn', 'categorise', 'image', 'label', 'examples', 'intf', 'categories', 'classify_image']

# %% app.ipynb 2
!pip install gradio
from fastai.vision.all import *
import gradio as gr

def is_cat(x): return x[0].isupper()

# %% app.ipynb 4
learn = load_learner('../input/model/model.pkl')

# %% app.ipynb 6
categorise = ('cat', 'dog')

def classify_image(img):
    pred,idx,probs = learn.predict(img)
    return dict(zip(categories, map(float,probs)))

# %% app.ipynb 7
image = gr.inputs.Image(shape=(192, 192))
label = gr.outputs.Label()
examples = ['../input/cat-dog/cat.jpg', '../input/cat-dog/dog.jpg']


intf = gr.Interface(fn=classify_image, inputs=image, outputs=label, examples=examples)
intf.launch(inline=False)

# %% app.ipynb 11
!pip install gradio
from fastai.vision.all import *
import gradio as gr

def is_cat(x): return x[0].isupper()

# %% app.ipynb 13
learn = load_learner('../input/model/model.pkl')

# %% app.ipynb 15
categories = ('cat', 'dog')

def classify_image(img):
    pred,idx,probs = learn.predict(img)
    return dict(zip(categories, map(float,probs)))

# %% app.ipynb 16
image = gr.inputs.Image(shape=(192, 192))
label = gr.outputs.Label()
examples = ['../input/cat-dog/cat.jpg', '../input/cat-dog/dog.jpg']


intf = gr.Interface(fn=classify_image, inputs=image, outputs=label, examples=examples)
intf.launch(inline=False)

# %% app.ipynb 22
!pip install gradio
from fastai.vision.all import *
import gradio as gr

def is_cat(x): return x[0].isupper()

# %% app.ipynb 24
learn = load_learner('../input/model/model.pkl')

# %% app.ipynb 26
categories = ('Dog', 'Cat')

def classify_image(img):
    pred,idx,probs = learn.predict(img)
    return dict(zip(categories, map(float,probs)))

# %% app.ipynb 27
image = gr.inputs.Image(shape=(192, 192))
label = gr.outputs.Label()
examples = ['../input/cat-dog/cat.jpg', '../input/cat-dog/dog.jpg']


intf = gr.Interface(fn=classify_image, inputs=image, outputs=label, examples=examples)
intf.launch(inline=False)

# %% app.ipynb 41
!pip install gradio
from fastai.vision.all import *
import gradio as gr

def is_cat(x): return x[0].isupper()

# %% app.ipynb 43
learn = load_learner('../input/model/model.pkl')

# %% app.ipynb 45
categories = ('Dog', 'Cat')

def classify_image(img):
    pred,idx,probs = learn.predict(img)
    return dict(zip(categories, map(float,probs)))

# %% app.ipynb 46
image = gr.inputs.Image(shape=(192, 192))
label = gr.outputs.Label()
examples = ['../input/cat-dog/cat.jpg', '../input/cat-dog/dog.jpg']


intf = gr.Interface(fn=classify_image, inputs=image, outputs=label, examples=examples)
intf.launch(inline=False)
